### ISSUE TITLE
DOCKER_BUILDKIT=1 docker build -f Dockerfile -t cphsieh/ruler:0.2.0 . excute wrong

### ISSUE THREAD

**Issue by yuanhang110** [NVIDIA/RULER#73]
1755.1   Getting requirements to build wheel: finished with status 'error'
1755.1   error: subprocess-exited-with-error
1755.1
1755.1   × Getting requirements to build wheel did not run successfully.
1755.1   │ exit code: 1
1755.1   ╰─> [23 lines of output]
1755.1       /tmp/pip-build-env-0249wcrs/overlay/local/lib/python3.10/dist-packages/_distutils_hack/__init__.py:53: UserWarning: Reliance on distutils from stdlib is deprecated. Users must rely on setuptools to provide the distutils module. Avoid importing distutils or import setuptools first, and avoid setting SETUPTOOLS_USE_DISTUTILS=stdlib. Register concerns at https://github.com/pypa/setuptools/issues/new?template=distutils-deprecation.yml
1755.1         warnings.warn(
1755.1       /tmp/pip-build-env-0249wcrs/overlay/local/lib/python3.10/dist-packages/torch/_subclasses/functional_tensor.py:258: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
1755.1         cpu = _conversion_method_template(device=torch.device("cpu"))
1755.1       fatal: not a git repository (or any of the parent directories): .git
1755.1       <string>:56: RuntimeWarning: Failed to get commit hash:
1755.1       Command '['git', 'rev-parse', 'HEAD']' returned non-zero exit status 128.
1755.1       Traceback (most recent call last):
1755.1         File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
1755.1           main()
1755.1         File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
1755.1           json_out['return_val'] = hook(**hook_input['kwargs'])
1755.1         File "/usr/local/lib/python3.10/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
1755.1           return hook(config_settings)
1755.1         File "/tmp/pip-build-env-0249wcrs/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 334, in get_requires_for_build_wheel
1755.1           return self._get_build_requires(config_settings, requirements=[])
1755.1         File "/tmp/pip-build-env-0249wcrs/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 304, in _get_build_requires
1755.1           self.run_setup()
1755.1         File "/tmp/pip-build-env-0249wcrs/overlay/local/lib/python3.10/dist-packages/setuptools/build_meta.py", line 320, in run_setup
1755.1           exec(code, locals())
1755.1         File "<string>", line 458, in <module>
1755.1         File "<string>", line 379, in get_vllm_version
1755.1       RuntimeError: Unknown runtime environment
1755.1       [end of output]
1755.1
1755.1   note: This error originates from a subprocess, and is likely not a problem with pip.
1761.9 error: subprocess-exited-with-error
1761.9
1761.9 × Getting requirements to build wheel did not run successfully.
1761.9 │ exit code: 1
1761.9 ╰─> See above for output.
1761.9
1761.9 note: This error originates from a subprocess, and is likely not a problem with pip.
------
Dockerfile:20
--------------------
  19 |     COPY ./requirements.txt .
  20 | >>> RUN pip install --upgrade pip \
  21 | >>>     && pip install -r requirements.txt \
  22 | >>>     && pip install flash-attn==2.6.0.post1 --no-build-isolation \
  23 | >>>     && pip install git+https://github.com/HazyResearch/flash-attention.git#subdirectory=csrc/rotary \
  24 | >>>     && pip install causal-conv1d==1.4.0 \
  25 | >>>     && pip install mamba-ssm==2.2.2
  26 |
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install --upgrade pip     && pip install -r requirements.txt     && pip install flash-attn==2.6.0.post1 --no-build-isolation     && pip install git+https://github.com/HazyResearch/flash-attention.git#subdirectory=csrc/rotary     && pip install causal-conv1d==1.4.0     && pip install mamba-ssm==2.2.2" did not complete successfully: exit code: 1

**Comment by hsiehjackson** [comment]
@yuanhang110 can you first check whether you can run container `nvcr.io/nvidia/pytorch:23.10-py3`?  Example command: 
`docker run --gpus all -it --rm --device=/dev/snd nvcr.io/nvidia/pytorch:23.10-py3`

**Comment by Linghao-Jin** [comment]
same here
